name: react-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use nodejs 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer depedencies
        run: npm install

      - name: Lint 
        run: npm run lint

      - name: Build React
        run: npm run build
